In [ ]:
# pip install wheel

In [ ]:
# !pip install plotly

In [ ]:
# pip install matplotlib

In [ ]:
# pip install pandas

In [ ]:
# pip install xlrd

In [ ]:
# pip install folium

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib 

#  df     = pd.DataFrame(credit_card_region_age)
# credit_card_region_age
# df.head()
# credit_card_region_age
# credit_card_data[credit_card_data['구분코드(pop_cd)'][i].find('L') ==1 ]
# credit_card_data[credit_card_data['구분코드(pop_cd)'].isin(['L0'])==1]
# credit_card_region_age = credit_card_data[credit_card_data['구분코드(pop_cd)'].map(lambda x : 'L' in x)]
# credit_card_age_sex = credit_card_data[credit_card_data['구분코드(pop_cd)'].map(lambda x : 'Y' in x)]

In [ ]:
#2 버전 확인
np.__version__, pd.__version__

('1.16.4', '1.0.5')

In [ ]:
# pip install matplotlib

In [ ]:
# 행정동 코드 
# 서울시_행정_법정동_코드.xlsx 
#CP949
path = 'D:/데이터/법정동코드/서울시_행정_법정동_코드.xlsx ' 
a=pd.read_excel(path,encoding='utf-8')
# 주어진 데이터의 컬럼 파트가 3개 라인을 사용하고 있어서 실제 데이터가 아닌 부분도 데이터로 표현이 된다.
# Case.columns =  [ '케이스번호','도시이름','구이름','그룹유무','감염경로','몇번째확진자','위도','경도']
a.head()

   자치구     행정동코드    행정동     법정동코드  법정동
0  종로구  11110515  청운효자동  11110101  청운동
1  종로구  11110515  청운효자동  11110102  신교동
2  종로구  11110515  청운효자동  11110103  궁정동
3  종로구  11110515  청운효자동  11110104  효자동
4  종로구  11110515  청운효자동  11110105  창성동

In [ ]:
a =a.sort_values(by='행정동코드')

In [ ]:
a['행정동코드'].unique()

array([11110515, 11110530, 11110540, 11110550, 11110560, 11110570,
       11110580, 11110600, 11110615, 11110630, 11110640, 11110650,
       11110660, 11110670, 11110680, 11110690, 11110700, 11110710,
       11140520, 11140540, 11140550, 11140570, 11140580, 11140590,
       11140605, 11140610, 11140620, 11140630, 11140640, 11140650,
       11140660, 11140670, 11140680, 11170510, 11170520, 11170530,
       11170555, 11170560, 11170570, 11170580, 11170590, 11170625,
       11170630, 11170640, 11170650, 11170660, 11170685, 11170690,
       11170700, 11200520, 11200535, 11200540, 11200550, 11200560,
       11200570, 11200580, 11200590, 11200615, 11200620, 11200645,
       11200650, 11200660, 11200670, 11200690, 11200720, 11200790,
       11215710, 11215730, 11215740, 11215750, 11215760, 11215770,
       11215780, 11215810, 11215820, 11215830, 11215840, 11215847,
       11215850, 11215860, 11215870, 11230536, 11230545, 11230560,
       11230570, 11230600, 11230610, 11230650, 11230660, 11230705,
       11230710, 11230720, 11230730, 11230740, 11230750, 11260000,
       11260520, 11260540, 11260550, 11260565, 11260570, 11260575,
       11260580, 11260590, 11260600, 11260610, 11260620, 11260630,
       11260655, 11260660, 11260680, 11260690, 11290525, 11290555,
       11290575, 11290580, 11290590, 11290600, 11290610, 11290620,
       11290630, 11290640, 11290650, 11290660, 11290685, 11290705,
       11290715, 11290725, 11290760, 11290770, 11290780, 11290810,
       11305534, 11305535, 11305545, 11305555, 11305575, 11305590,
       11305600, 11305606, 11305610, 11305620, 11305630, 11305645,
       11305660, 11320511, 11320512, 11320513, 11320514, 11320515,
       11320521, 11320522, 11320660, 11320670, 11320680, 11320681,
       11320690, 11320700, 11320710, 11350560, 11350570, 11350580,
       11350600, 11350605, 11350611, 11350612, 11350619, 11350621,
       11350624, 11350625, 11350630, 11350640, 11350665, 11350670,
       11350695, 11350700, 11350710, 11350720, 11380510, 11380520,
       11380530, 11380551, 11380552, 11380560, 11380570, 11380580,
       11380590, 11380600, 11380625, 11380631, 11380632, 11380640,
       11380650, 11380690, 11410520, 11410555, 11410565, 11410585,
       11410615, 11410620, 11410640, 11410655, 11410660, 11410685,
       11410690, 11410700, 11410710, 11410720, 11440555, 11440565,
       11440585, 11440590, 11440600, 11440610, 11440630, 11440655,
       11440660, 11440680, 11440690, 11440700, 11440710, 11440720,
       11440730, 11440740, 11470510, 11470520, 11470530, 11470540,
       11470550, 11470560, 11470570, 11470580, 11470590, 11470600,
       11470610, 11470611, 11470620, 11470630, 11470640, 11470650,
       11470670, 11470680, 11500510, 11500520, 11500530, 11500535,
       11500540, 11500550, 11500560, 11500570, 11500590, 11500591,
       11500593, 11500603, 11500604, 11500605, 11500611, 11500615,
       11500620, 11500630, 11500640, 11500641, 11530510, 11530520,
       11530530, 11530540, 11530550, 11530560, 11530595, 11530720,
       11530730, 11530740, 11530750, 11530760, 11530770, 11530780,
       11530790, 11545510, 11545610, 11545620, 11545630, 11545640,
       11545670, 11545680, 11545690, 11545700, 11545710, 11560515,
       11560535, 11560540, 11560550, 11560560, 11560585, 11560605,
       11560610, 11560620, 11560630, 11560650, 11560660, 11560670,
       11560680, 11560690, 11560700, 11560710, 11560720, 11590510,
       11590520, 11590530, 11590540, 11590550, 11590560, 11590605,
       11590620, 11590630, 11590640, 11590650, 11590651, 11590660,
       11590670, 11590680, 11620525, 11620545, 11620565, 11620575,
       11620585, 11620595, 11620605, 11620615, 11620625, 11620630,
       11620645, 11620655, 11620665, 11620685, 11620695, 11620715,
       11620725, 11620735, 11620745, 11620765, 11620775, 11650510,
       11650520, 11650530, 11650531, 11650540, 11650550, 11650560,
       11650570, 11650580, 11650581, 11650590, 11650600, 11650610,
       11650620, 11650621, 11650651, 11650652, 11650660, 11680510,
       11680521, 11680531, 11680545, 11680565, 11680580, 11680590,
       11680600, 11680610, 11680630, 11680640, 11680650, 11680655,
       11680656, 11680660, 11680670, 11680690, 11680700, 11680720,
       11680730, 11680740, 11680750, 11710510, 11710520, 11710531,
       11710532, 11710540, 11710550, 11710561, 11710562, 11710566,
       11710570, 11710580, 11710590, 11710600, 11710610, 11710620,
       11710631, 11710632, 11710641, 11710642, 11710646, 11710650,
       11710670, 11710680, 11710690, 11710710, 11710720, 11740515,
       11740520, 11740530, 11740540, 11740550, 11740560, 11740570,
       11740580, 11740590, 11740600, 11740610, 11740620, 11740640,
       11740650, 11740660, 11740685, 11740690, 11740700], dtype=int64)

In [ ]:
a2= a[['행정동코드','행정동']]

In [ ]:
pip install distributed

Collecting distributed
  Downloading distributed-2.21.0-py3-none-any.whl (646 kB)
Requirement already satisfied: dask>=2.9.0 in c:\users\master\appdata\local\programs\python\python37-32\lib\site-packages (from distributed) (2.21.0)
Collecting psutil>=5.0
  Downloading psutil-5.7.2-cp37-cp37m-win32.whl (238 kB)
Collecting toolz>=0.8.2
  Downloading toolz-0.10.0.tar.gz (49 kB)
Requirement already satisfied: pyyaml in c:\users\master\appdata\local\programs\python\python37-32\lib\site-packages (from distributed) (5.3.1)
Requirement already satisfied: setuptools in c:\users\master\appdata\local\programs\python\python37-32\lib\site-packages (from distributed) (41.2.0)
Collecting cloudpickle>=1.5.0
  Downloading cloudpickle-1.5.0-py3-none-any.whl (22 kB)
Collecting msgpack>=0.6.0
  Downloading msgpack-1.0.0-cp37-cp37m-win32.whl (63 kB)
Collecting zict>=0.1.3
  Downloading zict-2.0.0-py3-none-any.whl (10 kB)
Requirement already satisfied: click>=6.6 in c:\users\master\appdata\local\programs\python\python37-32\lib\site-packages (from distributed) (7.1.1)
Requirement already satisfied: tornado>=5; python_version < "3.8" in c:\users\master\appdata\local\programs\python\python37-32\lib\site-packages (from distributed) (6.0.4)
Collecting tblib>=1.6.0
  Downloading tblib-1.6.0-py2.py3-none-any.whl (12 kB)
Collecting sortedcontainers!=2.0.0,!=2.0.1
  Downloading sortedcontainers-2.2.2-py2.py3-none-any.whl (29 kB)
Collecting heapdict
  Downloading HeapDict-1.0.1-py3-none-any.whl (3.9 kB)
Building wheels for collected packages: toolz
  Building wheel for toolz (setup.py): started
  Building wheel for toolz (setup.py): finished with status 'done'
  Created wheel for toolz: filename=toolz-0.10.0-py3-none-any.whl size=55580 sha256=928c3c13f36bfcecafc5d766ca540cd4ebe7d274eb0e29fe12933ded4983d22c
  Stored in directory: c:\users\master\appdata\local\pip\cache\wheels\e2\83\7c\248063997a4f9ff6bf145822e620e8c37117a6b4c765584077
Successfully built toolz
Installing collected packages: psutil, toolz, cloudpickle, msgpack, heapdict, zict, tblib, sortedcontainers, distributed
Successfully installed cloudpickle-1.5.0 distributed-2.21.0 heapdict-1.0.1 msgpack-1.0.0 psutil-5.7.2 sortedcontainers-2.2.2 tblib-1.6.0 toolz-0.10.0 zict-2.0.0
Note: you may need to restart the kernel to use updated packages.

In [ ]:
pip install modin

Collecting modinNote: you may need to restart the kernel to use updated packages.
  Downloading modin-0.7.4-py3-none-win32.whl (334 kB)
Requirement already satisfied: pandas==1.0.5 in c:\users\master\appdata\local\programs\python\python37-32\lib\site-packages (from modin) (1.0.5)
Requirement already satisfied: packaging in c:\users\master\appdata\local\programs\python\python37-32\lib\site-packages (from modin) (20.4)
Requirement already satisfied: pytz>=2017.2 in c:\users\master\appdata\local\programs\python\python37-32\lib\site-packages (from pandas==1.0.5->modin) (2019.3)
Requirement already satisfied: numpy>=1.13.3 in c:\users\master\appdata\roaming\python\python37\site-packages (from pandas==1.0.5->modin) (1.16.4)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\master\appdata\local\programs\python\python37-32\lib\site-packages (from pandas==1.0.5->modin) (2.8.1)
Requirement already satisfied: six in c:\users\master\appdata\local\programs\python\python37-32\lib\site-packages (from packaging->modin) (1.14.0)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\master\appdata\local\programs\python\python37-32\lib\site-packages (from packaging->modin) (2.4.7)
Installing collected packages: modin
Successfully installed modin-0.7.4

In [ ]:
import modin.pandas as pd4

UserWarning: The Dask Engine for Modin is experimental.

In [ ]:
path = f'D:/데이터/유동인구/LOCAL_PEOPLE_DONG_202001.csv' 
b =pd.read_csv(path,encoding='utf-8')
# 주어진 데이터의 컬럼 파트가 3개 라인을 사용하고 있어서 실제 데이터가 아닌 부분도 데이터로 표현이 된다.
# Case.columns =  [ '케이스번호','도시이름','구이름','그룹유무','감염경로','몇번째확진자','위도','경도']
b.reset_index(inplace=True)
bcolumns = b.columns
 
b.drop('여자70세이상생활인구수',axis=1,inplace=True)
b.drop('여자55세부터59세생활인구수',axis=1,inplace=True)
b.drop('여자50세부터54세생활인구수',axis=1,inplace=True)
b.drop('여자65세부터69세생활인구수',axis=1,inplace=True)
b.drop('여자60세부터64세생활인구수',axis=1,inplace=True)
b.drop('여자45세부터49세생활인구수',axis=1,inplace=True)


b.columns =  bcolumns[6:]
# len(bcolumns[6:]) , len(b.columns )

In [ ]:
b

,기준일ID,시간대구분,행정동코드,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
0,20200101,0,11620625,24188.5806,870.1487,439.6648,453.6983,683.2883,1348.9122,1230.3016,...,1381.5367,1264.4003,1112.2324,889.4873,864.8068,832.7668,825.7571,777.3297,708.1216,1501.7124
1,20200101,0,11140605,6716.5334,89.0565,36.2822,78.8508,225.3331,416.2471,321.9111,...,439.5516,314.3750,209.5565,156.2364,171.9298,203.5514,248.0982,145.9047,139.5027,303.8293
2,20200101,0,11470640,46603.6243,2164.9685,1254.3274,1296.7883,1076.9660,1164.2301,1271.9820,...,1318.5467,1510.0550,1877.1880,1947.7351,2149.1684,1894.8391,1964.5647,1812.9103,1473.4635,3226.1966
3,20200101,0,11290780,9589.1813,390.6835,244.4328,192.6254,240.5164,288.9657,301.6838,...,273.5978,323.4285,395.5678,375.7008,416.7873,327.9834,380.6776,385.1141,311.8604,697.1448
4,20200101,0,11320512,29984.1309,1005.9128,506.6446,637.8008,721.4613,1013.8781,972.6073,...,1079.7667,1071.6117,1332.6363,1053.3402,1345.4963,1144.1586,1397.3890,1362.8639,881.4148,2509.3527
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315451,20200131,23,11260690,20052.7278,784.8522,457.1949,526.8845,426.1374,584.2272,615.6149,...,635.1490,671.0664,750.8707,699.8694,743.0368,843.0214,931.0432,884.6889,517.3753,1753.4643
315452,20200131,23,11140570,7758.9907,143.6706,47.8903,187.4134,509.5091,426.2835,362.9879,...,351.4894,274.5788,216.8041,173.7629,216.3448,236.3069,219.1106,270.4115,150.0009,451.9609
315453,20200131,23,11590605,34441.9618,1054.0754,489.3910,760.0268,1650.0129,1779.6227,1149.3261,...,1401.7873,1095.0137,1390.1508,1249.4925,1246.8999,1104.3225,1438.1116,1222.5712,827.5667,2785.4229
315454,20200131,23,11215760,17221.9293,535.6532,264.8733,357.2389,398.5186,686.9233,669.1286,...,724.3769,803.4801,674.3875,605.0563,665.1922,699.7245,802.7436,798.3434,495.4902,1155.2362
315455,20200131,23,11200580,15466.1528,629.6817,386.2273,387.2891,266.1634,331.7367,443.1860,...,420.2659,599.6902,817.2965,707.4142,768.5882,519.8206,570.3165,522.0797,475.4052,1376.0874

In [ ]:
# 행정동 코드 
# 유동인구 202006
2#LOCAL_PEOPLE_DONG_202006.csv
path = 'D:/데이터/유동인구/LOCAL_PEOPLE_DONG_202001.csv' 
b =pd.read_csv(path,sep=',',encoding='utf-8') 

# 주어진 데이터의 컬럼 파트가 3개 라인을 사용하고 있어서 실제 데이터가 아닌 부분도 데이터로 표현이 된다.
# Case.columns =  [ '케이스번호','도시이름','구이름','그룹유무','감염경로','몇번째확진자','위도','경도']
# b.reset_index(inplace=True)
# bcolumns = b.columns
# bcolumns 
# b.drop('여자70세이상생활인구수',axis=1,inplace=True)
# b.columns =  bcolumns[1:]

In [ ]:
b

                                                         기준일ID      시간대구분  \
20200101 0  11620625 24188.5806 870.1487  439.6648    453.6983   683.2883
            11140605 6716.5334  89.0565   36.2822      78.8508   225.3331
            11470640 46603.6243 2164.9685 1254.3274  1296.7883  1076.9660
            11290780 9589.1813  390.6835  244.4328    192.6254   240.5164
            11320512 29984.1309 1005.9128 506.6446    637.8008   721.4613
...                                                        ...        ...
20200131 23 11260690 20052.7278 784.8522  457.1949    526.8845   426.1374
            11140570 7758.9907  143.6706  47.8903     187.4134   509.5091
            11590605 34441.9618 1054.0754 489.3910    760.0268  1650.0129
            11215760 17221.9293 535.6532  264.8733    357.2389   398.5186
            11200580 15466.1528 629.6817  386.2273    387.2891   266.1634

                                                         행정동코드     총생활인구수  \
20200101 0  11620625 24188.5806 870.1487  439.6648   1348.9122  1230.3016
            11140605 6716.5334  89.0565   36.2822     416.2471   321.9111
            11470640 46603.6243 2164.9685 1254.3274  1164.2301  1271.9820
            11290780 9589.1813  390.6835  244.4328    288.9657   301.6838
            11320512 29984.1309 1005.9128 506.6446   1013.8781   972.6073
...                                                        ...        ...
20200131 23 11260690 20052.7278 784.8522  457.1949    584.2272   615.6149
            11140570 7758.9907  143.6706  47.8903     426.2835   362.9879
            11590605 34441.9618 1054.0754 489.3910   1779.6227  1149.3261
            11215760 17221.9293 535.6532  264.8733    686.9233   669.1286
            11200580 15466.1528 629.6817  386.2273    331.7367   443.1860

                                                     남자0세부터9세생활인구수  \
20200101 0  11620625 24188.5806 870.1487  439.6648       1241.8060
            11140605 6716.5334  89.0565   36.2822         384.6804
            11470640 46603.6243 2164.9685 1254.3274      1612.2681
            11290780 9589.1813  390.6835  244.4328        422.9831
            11320512 29984.1309 1005.9128 506.6446       1399.1344
...                                                            ...
20200131 23 11260690 20052.7278 784.8522  457.1949        771.0202
            11140570 7758.9907  143.6706  47.8903         389.0069
            11590605 34441.9618 1054.0754 489.3910       1372.0159
            11215760 17221.9293 535.6532  264.8733        732.5289
            11200580 15466.1528 629.6817  386.2273        634.6226

                                                     남자10세부터14세생활인구수  \
20200101 0  11620625 24188.5806 870.1487  439.6648          977.0445
            11140605 6716.5334  89.0565   36.2822           319.6471
            11470640 46603.6243 2164.9685 1254.3274        1789.7598
            11290780 9589.1813  390.6835  244.4328          416.2920
            11320512 29984.1309 1005.9128 506.6446         1136.1888
...                                                              ...
20200131 23 11260690 20052.7278 784.8522  457.1949          699.3425
            11140570 7758.9907  143.6706  47.8903           383.9145
            11590605 34441.9618 1054.0754 489.3910         1230.6938
            11215760 17221.9293 535.6532  264.8733          589.0981
            11200580 15466.1528 629.6817  386.2273          664.7118

                                                     남자15세부터19세생활인구수  \
20200101 0  11620625 24188.5806 870.1487  439.6648          904.4887
            11140605 6716.5334  89.0565   36.2822           439.3991
            11470640 46603.6243 2164.9685 1254.3274        2167.3258
            11290780 9589.1813  390.6835  244.4328          374.5834
            11320512 29984.1309 1005.9128 506.6446         1196.0817
...                                                              ...
20200131 23 11260690 20052.7278 784.8522  457.1949          813.6781
            11140570 7758.9907  143.6706  47.8903           480.3384
            11590605 34441.9618 1054.0754 489.3910         1310.8027
            11215760 17221.9293 535.6532  264.8733          624.0481
            11200580 15466.1528 629.6817  386.2273          695.1976

                                                     남자20세부터24세생활인구수  \
20200101 0  11620625 24188.5806 870.1487  439.6648          686.2733
            11140605 6716.5334  89.0565   36.2822           317.5785
            11470640 46603.6243 2164.9685 1254.3274        1724.0015
            11290780 9589.1813  390.6835  244.4328          352.5476
            11320512 29984.1309 1005.9128 506.6446         1060.0758
...                                                              ...
20200131 23 11260690 20052.7278 784.8522  457.1949          699.6770
            11140570 7758.9907  143.6706  47.8903           352.4011
            11590605 34441.9618 1054.0754 489.3910         1103.9641
            11215760 17221.9293 535.6532  264.8733          674.3665
            11200580 15466.1528 629.6817  386.2273          553.1253

                                                     남자25세부터29세생활인구수  \
20200101 0  11620625 24188.5806 870.1487  439.6648          690.4204
            11140605 6716.5334  89.0565   36.2822           405.7616
            11470640 46603.6243 2164.9685 1254.3274        1647.8361
            11290780 9589.1813  390.6835  244.4328          371.2832
            11320512 29984.1309 1005.9128 506.6446         1125.1947
...                                                              ...
20200131 23 11260690 20052.7278 784.8522  457.1949          851.1038
            11140570 7758.9907  143.6706  47.8903           368.0744
            11590605 34441.9618 1054.0754 489.3910         1185.3104
            11215760 17221.9293 535.6532  264.8733          803.5019
            11200580 15466.1528 629.6817  386.2273          550.5858

                                                     남자30세부터34세생활인구수  ...  \
20200101 0  11620625 24188.5806 870.1487  439.6648          551.8501  ...
            11140605 6716.5334  89.0565   36.2822           278.6440  ...
            11470640 46603.6243 2164.9685 1254.3274        1410.4441  ...
            11290780 9589.1813  390.6835  244.4328          332.1322  ...
            11320512 29984.1309 1005.9128 506.6446         1032.2647  ...
...                                                              ...  ...
20200131 23 11260690 20052.7278 784.8522  457.1949          738.8965  ...
            11140570 7758.9907  143.6706  47.8903           231.6215  ...
            11590605 34441.9618 1054.0754 489.3910          966.8522  ...
            11215760 17221.9293 535.6532  264.8733          590.9015  ...
            11200580 15466.1528 629.6817  386.2273          375.9853  ...

                                                     여자25세부터29세생활인구수  \
20200101 0  11620625 24188.5806 870.1487  439.6648          825.7571
            11140605 6716.5334  89.0565   36.2822           248.0982
            11470640 46603.6243 2164.9685 1254.3274        1964.5647
            11290780 9589.1813  390.6835  244.4328          380.6776
            11320512 29984.1309 1005.9128 506.6446         1397.3890
...                                                              ...
20200131 23 11260690 20052.7278 784.8522  457.1949          931.0432
            11140570 7758.9907  143.6706  47.8903           219.1106
            11590605 34441.9618 1054.0754 489.3910         1438.1116
            11215760 17221.9293 535.6532  264.8733          802.7436
            11200580 15466.1528 629.6817  386.2273          570.3165

                                                     여자30세부터34세생활인구수  \
20200101 0  11620625 24188.5806 870.1487  439.6648          777.3297
            11140605 6716.5334  89.0565   36.2822           145.9047
            11470640 46603.6243 2164.9685 1254.3274        1812.9103
            11290780 9589.1813  390.6835  244.4328          385.1141
            11320512 29984.1309 1005.9128 506.6446         1362.8639
...                                                              ...
20200131 23 11260690 20052.7278 784.8522  457.1949          884.6889
            11140570 7758.9907  143.6706  47.8903           270.4115
            11590605 34441.9618 1054.0754 489.3910         1222.5712
            11215760 17221.9293 535.6532  264.8733          798.3434
            11200580 15466.1528 629.6817  386.2273          522.0797

                                                     여자35세부터39세생활인구수  \
20200101 0  11620625 24188.5806 870.1487  439.6648          708.1216
            11140605 6716.5334  89.0565   36.2822           139.5027
            11470640 46603.6243 2164.9685 1254.3274        1473.4635
            11290780 9589.1813  390.6835  244.4328          311.8604
            11320512 29984.1309 1005.9128 506.6446          881.4148
...                                                              ...
20200131 23 11260690 20052.7278 784.8522  457.1949          517.3753
            11140570 7758.9907  143.6706  47.8903           150.0009
            11590605 34441.9618 1054.0754 489.3910          827.5667
            11215760 17221.9293 535.6532  264.8733          495.4902
            11200580 15466.1528 629.6817  386.2273          475.4052

                                                     여자40세부터44세생활인구수  \
20200101 0  11620625 24188.5806 870.1487  439.6648         1501.7124
            11140605 6716.5334  89.0565   36.2822           303.8293
            11470640 46603.6243 2164.9685 1254.3274        3226.1966
            11290780 9589.1813  390.6835  244.4328          697.1448
            11320512 29984.1309 1005.9128 506.6446         2509.3527
...                                                              ...
20200131 23 11260690 20052.7278 784.8522  457.1949         1753.4643
            11140570 7758.9907  143.6706  47.8903           451.9609
            11590605 34441.9618 1054.0754 489.3910         2785.4229
            11215760 17221.9293 535.6532  264.8733         1155.2362
            11200580 15466.1528 629.6817  386.2273         1376.0874

                                                     여자45세부터49세생활인구수  \
20200101 0  11620625 24188.5806 870.1487  439.6648               NaN
            11140605 6716.5334  89.0565   36.2822                NaN
            11470640 46603.6243 2164.9685 1254.3274              NaN
            11290780 9589.1813  390.6835  244.4328               NaN
            11320512 29984.1309 1005.9128 506.6446               NaN
...                                                              ...
20200131 23 11260690 20052.7278 784.8522  457.1949               NaN
            11140570 7758.9907  143.6706  47.8903                NaN
            11590605 34441.9618 1054.0754 489.3910               NaN
            11215760 17221.9293 535.6532  264.8733               NaN
            11200580 15466.1528 629.6817  386.2273               NaN

                                                     여자50세부터54세생활인구수  \
20200101 0  11620625 24188.5806 870.1487  439.6648               NaN
            11140605 6716.5334  89.0565   36.2822                NaN
            11470640 46603.6243 2164.9685 1254.3274              NaN
            11290780 9589.1813  390.6835  244.4328               NaN
            11320512 29984.1309 1005.9128 506.6446               NaN
...                                                              ...
20200131 23 11260690 20052.7278 784.8522  457.1949               NaN
            11140570 7758.9907  143.6706  47.8903                NaN
            11590605 34441.9618 1054.0754 489.3910               NaN
            11215760 17221.9293 535.6532  264.8733               NaN
            11200580 15466.1528 629.6817  386.2273               NaN

                                                     여자55세부터59세생활인구수  \
20200101 0  11620625 24188.5806 870.1487  439.6648               NaN
            11140605 6716.5334  89.0565   36.2822                NaN
            11470640 46603.6243 2164.9685 1254.3274              NaN
            11290780 9589.1813  390.6835  244.4328               NaN
            11320512 29984.1309 1005.9128 506.6446               NaN
...                                                              ...
20200131 23 11260690 20052.7278 784.8522  457.1949               NaN
            11140570 7758.9907  143.6706  47.8903                NaN
            11590605 34441.9618 1054.0754 489.3910               NaN
            11215760 17221.9293 535.6532  264.8733               NaN
            11200580 15466.1528 629.6817  386.2273               NaN

                                                     여자60세부터64세생활인구수  \
20200101 0  11620625 24188.5806 870.1487  439.6648               NaN
            11140605 6716.5334  89.0565   36.2822                NaN
            11470640 46603.6243 2164.9685 1254.3274              NaN
            11290780 9589.1813  390.6835  244.4328               NaN
            11320512 29984.1309 1005.9128 506.6446               NaN
...                                                              ...
20200131 23 11260690 20052.7278 784.8522  457.1949               NaN
            11140570 7758.9907  143.6706  47.8903                NaN
            11590605 34441.9618 1054.0754 489.3910               NaN
            11215760 17221.9293 535.6532  264.8733               NaN
            11200580 15466.1528 629.6817  386.2273               NaN

                                                     여자65세부터69세생활인구수  \
20200101 0  11620625 24188.5806 870.1487  439.6648               NaN
            11140605 6716.5334  89.0565   36.2822                NaN
            11470640 46603.6243 2164.9685 1254.3274              NaN
            11290780 9589.1813  390.6835  244.4328               NaN
            11320512 29984.1309 1005.9128 506.6446               NaN
...                                                              ...
20200131 23 11260690 20052.7278 784.8522  457.1949               NaN
            11140570 7758.9907  143.6706  47.8903                NaN
            11590605 34441.9618 1054.0754 489.3910               NaN
            11215760 17221.9293 535.6532  264.8733               NaN
            11200580 15466.1528 629.6817  386.2273               NaN

                                                     여자70세이상생활인구수
20200101 0  11620625 24188.5806 870.1487  439.6648            NaN
            11140605 6716.5334  89.0565   36.2822             NaN
            11470640 46603.6243 2164.9685 1254.3274           NaN
            11290780 9589.1813  390.6835  244.4328            NaN
            11320512 29984.1309 1005.9128 506.6446            NaN
...                                                           ...
20200131 23 11260690 20052.7278 784.8522  457.1949            NaN
            11140570 7758.9907  143.6706  47.8903             NaN
            11590605 34441.9618 1054.0754 489.3910            NaN
            11215760 17221.9293 535.6532  264.8733            NaN
            11200580 15466.1528 629.6817  386.2273            NaN

[315456 rows x 32 columns]

In [ ]:
df = pd.concat(dfList,sort=False)

In [ ]:
df

                                                         기준일ID      시간대구분  \
20170201 0  11110515 14905.2320 565.8853  360.5835    405.1086   589.5560
            11110530 18336.8186 359.8342  159.9262    213.7376   720.0792
            11110540 4233.0345  64.6494   49.5368     119.1041   220.3922
            11110550 11628.9183 266.6229  206.7356    330.2458   385.8279
            11110560 25155.4005 636.5953  460.4703    633.9927   782.0635
...                                                        ...        ...
20170228 23 11740650 30617.9765 841.9938  292.0766    656.9691  1000.5545
            11740660 33629.5517 913.0094  548.8090   1107.6129  1179.3479
            11740685 61176.0497 2166.0101 1047.4096  1422.3902  1620.9630
            11740690 15062.2880 306.3420  232.1755    670.3566   595.3452
            11740700 38440.4324 1527.5537 770.5807   1022.0582  1135.2642

                                                         행정동코드     총생활인구수  \
20170201 0  11110515 14905.2320 565.8853  360.5835    539.0759   524.4735
            11110530 18336.8186 359.8342  159.9262    761.4362   720.5611
            11110540 4233.0345  64.6494   49.5368     232.8157   195.3879
            11110550 11628.9183 266.6229  206.7356    387.2692   274.9438
            11110560 25155.4005 636.5953  460.4703    684.0409   549.5666
...                                                        ...        ...
20170228 23 11740650 30617.9765 841.9938  292.0766   1405.1449  1384.5190
            11740660 33629.5517 913.0094  548.8090   1369.9855  1404.6759
            11740685 61176.0497 2166.0101 1047.4096  2138.1575  2483.9234
            11740690 15062.2880 306.3420  232.1755    461.7753   334.2264
            11740700 38440.4324 1527.5537 770.5807   1147.8210  1227.5255

                                                     남자0세부터9세생활인구수  \
20170201 0  11110515 14905.2320 565.8853  360.5835        621.9373
            11110530 18336.8186 359.8342  159.9262        881.9947
            11110540 4233.0345  64.6494   49.5368         189.2281
            11110550 11628.9183 266.6229  206.7356        333.6206
            11110560 25155.4005 636.5953  460.4703        708.7414
...                                                            ...
20170228 23 11740650 30617.9765 841.9938  292.0766       1550.4709
            11740660 33629.5517 913.0094  548.8090       1602.8613
            11740685 61176.0497 2166.0101 1047.4096      2856.4045
            11740690 15062.2880 306.3420  232.1755        319.4626
            11740700 38440.4324 1527.5537 770.5807       1350.5264

                                                     남자10세부터14세생활인구수  \
20170201 0  11110515 14905.2320 565.8853  360.5835          601.4154
            11110530 18336.8186 359.8342  159.9262          943.2036
            11110540 4233.0345  64.6494   49.5368           166.9493
            11110550 11628.9183 266.6229  206.7356          364.3777
            11110560 25155.4005 636.5953  460.4703          802.4587
...                                                              ...
20170228 23 11740650 30617.9765 841.9938  292.0766         1195.8133
            11740660 33629.5517 913.0094  548.8090         1259.2086
            11740685 61176.0497 2166.0101 1047.4096        2392.7490
            11740690 15062.2880 306.3420  232.1755          332.2679
            11740700 38440.4324 1527.5537 770.5807         1139.4934

                                                     남자15세부터19세생활인구수  \
20170201 0  11110515 14905.2320 565.8853  360.5835          639.9276
            11110530 18336.8186 359.8342  159.9262          820.1767
            11110540 4233.0345  64.6494   49.5368           191.5223
            11110550 11628.9183 266.6229  206.7356          461.4576
            11110560 25155.4005 636.5953  460.4703          980.8386
...                                                              ...
20170228 23 11740650 30617.9765 841.9938  292.0766         1075.7776
            11740660 33629.5517 913.0094  548.8090         1411.1882
            11740685 61176.0497 2166.0101 1047.4096        2377.2462
            11740690 15062.2880 306.3420  232.1755          562.5856
            11740700 38440.4324 1527.5537 770.5807         1294.5353

                                                     남자20세부터24세생활인구수  \
20170201 0  11110515 14905.2320 565.8853  360.5835          549.9389
            11110530 18336.8186 359.8342  159.9262          712.5590
            11110540 4233.0345  64.6494   49.5368           144.3004
            11110550 11628.9183 266.6229  206.7356          403.3317
            11110560 25155.4005 636.5953  460.4703          896.1842
...                                                              ...
20170228 23 11740650 30617.9765 841.9938  292.0766          907.3795
            11740660 33629.5517 913.0094  548.8090         1147.8868
            11740685 61176.0497 2166.0101 1047.4096        2145.9450
            11740690 15062.2880 306.3420  232.1755          674.2714
            11740700 38440.4324 1527.5537 770.5807         1257.3416

                                                     남자25세부터29세생활인구수  \
20170201 0  11110515 14905.2320 565.8853  360.5835          444.3570
            11110530 18336.8186 359.8342  159.9262          661.6275
            11110540 4233.0345  64.6494   49.5368           133.7241
            11110550 11628.9183 266.6229  206.7356          416.8790
            11110560 25155.4005 636.5953  460.4703          948.0424
...                                                              ...
20170228 23 11740650 30617.9765 841.9938  292.0766         1180.9051
            11740660 33629.5517 913.0094  548.8090         1151.8720
            11740685 61176.0497 2166.0101 1047.4096        2241.0009
            11740690 15062.2880 306.3420  232.1755          786.6159
            11740700 38440.4324 1527.5537 770.5807         1606.4140

                                                     남자30세부터34세생활인구수  ...  \
20170201 0  11110515 14905.2320 565.8853  360.5835          305.4187  ...
            11110530 18336.8186 359.8342  159.9262          604.0072  ...
            11110540 4233.0345  64.6494   49.5368           120.3660  ...
            11110550 11628.9183 266.6229  206.7356          442.5254  ...
            11110560 25155.4005 636.5953  460.4703         1049.9516  ...
...                                                              ...  ...
20170228 23 11740650 30617.9765 841.9938  292.0766          782.3930  ...
            11740660 33629.5517 913.0094  548.8090         1030.7708  ...
            11740685 61176.0497 2166.0101 1047.4096        2096.6642  ...
            11740690 15062.2880 306.3420  232.1755          735.7478  ...
            11740700 38440.4324 1527.5537 770.5807         1319.7478  ...

                                                     여자25세부터29세생활인구수  \
20170201 0  11110515 14905.2320 565.8853  360.5835          483.0048
            11110530 18336.8186 359.8342  159.9262          687.4086
            11110540 4233.0345  64.6494   49.5368           143.4352
            11110550 11628.9183 266.6229  206.7356          462.0503
            11110560 25155.4005 636.5953  460.4703         1266.0107
...                                                              ...
20170228 23 11740650 30617.9765 841.9938  292.0766         1499.7811
            11740660 33629.5517 913.0094  548.8090         1540.1606
            11740685 61176.0497 2166.0101 1047.4096        3256.4302
            11740690 15062.2880 306.3420  232.1755         1034.6866
            11740700 38440.4324 1527.5537 770.5807         1954.7155

                                                     여자30세부터34세생활인구수  \
20170201 0  11110515 14905.2320 565.8853  360.5835          422.8816
            11110530 18336.8186 359.8342  159.9262          620.2346
            11110540 4233.0345  64.6494   49.5368           147.5187
            11110550 11628.9183 266.6229  206.7356          503.5685
            11110560 25155.4005 636.5953  460.4703         1091.9057
...                                                              ...
20170228 23 11740650 30617.9765 841.9938  292.0766         1386.7642
            11740660 33629.5517 913.0094  548.8090         1380.1660
            11740685 61176.0497 2166.0101 1047.4096        2587.7450
            11740690 15062.2880 306.3420  232.1755          718.9180
            11740700 38440.4324 1527.5537 770.5807         1876.4645

                                                     여자35세부터39세생활인구수  \
20170201 0  11110515 14905.2320 565.8853  360.5835          348.2906
            11110530 18336.8186 359.8342  159.9262          480.4984
            11110540 4233.0345  64.6494   49.5368           117.8847
            11110550 11628.9183 266.6229  206.7356          398.1867
            11110560 25155.4005 636.5953  460.4703          807.5647
...                                                              ...
20170228 23 11740650 30617.9765 841.9938  292.0766          900.6636
            11740660 33629.5517 913.0094  548.8090         1039.1921
            11740685 61176.0497 2166.0101 1047.4096        1928.5197
            11740690 15062.2880 306.3420  232.1755          421.9436
            11740700 38440.4324 1527.5537 770.5807         1254.0825

                                                     여자40세부터44세생활인구수  \
20170201 0  11110515 14905.2320 565.8853  360.5835         1271.1488
            11110530 18336.8186 359.8342  159.9262         1786.7725
            11110540 4233.0345  64.6494   49.5368           453.0185
            11110550 11628.9183 266.6229  206.7356         1135.3646
            11110560 25155.4005 636.5953  460.4703         2848.1005
...                                                              ...
20170228 23 11740650 30617.9765 841.9938  292.0766         1951.1967
            11740660 33629.5517 913.0094  548.8090         1883.2813
            11740685 61176.0497 2166.0101 1047.4096        3482.5665
            11740690 15062.2880 306.3420  232.1755          994.3392
            11740700 38440.4324 1527.5537 770.5807         2471.1385

                                                     여자45세부터49세생활인구수  \
20170201 0  11110515 14905.2320 565.8853  360.5835               NaN
            11110530 18336.8186 359.8342  159.9262               NaN
            11110540 4233.0345  64.6494   49.5368                NaN
            11110550 11628.9183 266.6229  206.7356               NaN
            11110560 25155.4005 636.5953  460.4703               NaN
...                                                              ...
20170228 23 11740650 30617.9765 841.9938  292.0766               NaN
            11740660 33629.5517 913.0094  548.8090               NaN
            11740685 61176.0497 2166.0101 1047.4096              NaN
            11740690 15062.2880 306.3420  232.1755               NaN
            11740700 38440.4324 1527.5537 770.5807               NaN

                                                     여자50세부터54세생활인구수  \
20170201 0  11110515 14905.2320 565.8853  360.5835               NaN
            11110530 18336.8186 359.8342  159.9262               NaN
            11110540 4233.0345  64.6494   49.5368                NaN
            11110550 11628.9183 266.6229  206.7356               NaN
            11110560 25155.4005 636.5953  460.4703               NaN
...                                                              ...
20170228 23 11740650 30617.9765 841.9938  292.0766               NaN
            11740660 33629.5517 913.0094  548.8090               NaN
            11740685 61176.0497 2166.0101 1047.4096              NaN
            11740690 15062.2880 306.3420  232.1755               NaN
            11740700 38440.4324 1527.5537 770.5807               NaN

                                                     여자55세부터59세생활인구수  \
20170201 0  11110515 14905.2320 565.8853  360.5835               NaN
            11110530 18336.8186 359.8342  159.9262               NaN
            11110540 4233.0345  64.6494   49.5368                NaN
            11110550 11628.9183 266.6229  206.7356               NaN
            11110560 25155.4005 636.5953  460.4703               NaN
...                                                              ...
20170228 23 11740650 30617.9765 841.9938  292.0766               NaN
            11740660 33629.5517 913.0094  548.8090               NaN
            11740685 61176.0497 2166.0101 1047.4096              NaN
            11740690 15062.2880 306.3420  232.1755               NaN
            11740700 38440.4324 1527.5537 770.5807               NaN

                                                     여자60세부터64세생활인구수  \
20170201 0  11110515 14905.2320 565.8853  360.5835               NaN
            11110530 18336.8186 359.8342  159.9262               NaN
            11110540 4233.0345  64.6494   49.5368                NaN
            11110550 11628.9183 266.6229  206.7356               NaN
            11110560 25155.4005 636.5953  460.4703               NaN
...                                                              ...
20170228 23 11740650 30617.9765 841.9938  292.0766               NaN
            11740660 33629.5517 913.0094  548.8090               NaN
            11740685 61176.0497 2166.0101 1047.4096              NaN
            11740690 15062.2880 306.3420  232.1755               NaN
            11740700 38440.4324 1527.5537 770.5807               NaN

                                                     여자65세부터69세생활인구수  \
20170201 0  11110515 14905.2320 565.8853  360.5835               NaN
            11110530 18336.8186 359.8342  159.9262               NaN
            11110540 4233.0345  64.6494   49.5368                NaN
            11110550 11628.9183 266.6229  206.7356               NaN
            11110560 25155.4005 636.5953  460.4703               NaN
...                                                              ...
20170228 23 11740650 30617.9765 841.9938  292.0766               NaN
            11740660 33629.5517 913.0094  548.8090               NaN
            11740685 61176.0497 2166.0101 1047.4096              NaN
            11740690 15062.2880 306.3420  232.1755               NaN
            11740700 38440.4324 1527.5537 770.5807               NaN

                                                     여자70세이상생활인구수
20170201 0  11110515 14905.2320 565.8853  360.5835            NaN
            11110530 18336.8186 359.8342  159.9262            NaN
            11110540 4233.0345  64.6494   49.5368             NaN
            11110550 11628.9183 266.6229  206.7356            NaN
            11110560 25155.4005 636.5953  460.4703            NaN
...                                                           ...
20170228 23 11740650 30617.9765 841.9938  292.0766            NaN
            11740660 33629.5517 913.0094  548.8090            NaN
            11740685 61176.0497 2166.0101 1047.4096           NaN
            11740690 15062.2880 306.3420  232.1755            NaN
            11740700 38440.4324 1527.5537 770.5807            NaN

[284928 rows x 32 columns]

In [ ]:
len(b['행정동코드'].unique()) , len(a['행정동코드'].unique())

(424, 425)

In [ ]:
#11500611
b['행정동코드'].unique().sort()
# a['행정동코드'].unique()
b['행정동코드'].min()
b.shape

(305280, 32)

In [ ]:
a['행정동코드'].min()
a.shape
a2.shape

(731, 2)

In [ ]:
pd.merge(b,a, on='행정동코드')

,기준일ID,시간대구분,행정동코드,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,...,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수,자치구,행정동,법정동코드,법정동
0,20200601,0,11110515,14493.2553,524.8395,334.4289,482.7069,611.7665,501.7881,396.2501,...,733.1297,648.2231,548.7319,433.5223,364.9237,1081.1082,종로구,청운효자동,11110101,청운동
1,20200601,0,11110515,14493.2553,524.8395,334.4289,482.7069,611.7665,501.7881,396.2501,...,733.1297,648.2231,548.7319,433.5223,364.9237,1081.1082,종로구,청운효자동,11110102,신교동
2,20200601,0,11110515,14493.2553,524.8395,334.4289,482.7069,611.7665,501.7881,396.2501,...,733.1297,648.2231,548.7319,433.5223,364.9237,1081.1082,종로구,청운효자동,11110103,궁정동
3,20200601,0,11110515,14493.2553,524.8395,334.4289,482.7069,611.7665,501.7881,396.2501,...,733.1297,648.2231,548.7319,433.5223,364.9237,1081.1082,종로구,청운효자동,11110104,효자동
4,20200601,0,11110515,14493.2553,524.8395,334.4289,482.7069,611.7665,501.7881,396.2501,...,733.1297,648.2231,548.7319,433.5223,364.9237,1081.1082,종로구,청운효자동,11110105,창성동
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519115,20200630,21,11500611,35834.9557,2097.1081,1124.1170,1362.9480,889.1129,855.2962,827.1172,...,1691.8015,1082.1757,1320.2722,1057.3133,827.5814,1778.6805,강서구,발산제1동,11500107,외발산동
519116,20200630,22,11500611,36109.8877,2160.3213,1158.0011,1346.1533,861.9482,910.3998,853.5796,...,1707.8444,1135.6293,1279.8286,1078.0385,800.7071,1830.5647,강서구,발산제1동,11500106,내발산동
519117,20200630,22,11500611,36109.8877,2160.3213,1158.0011,1346.1533,861.9482,910.3998,853.5796,...,1707.8444,1135.6293,1279.8286,1078.0385,800.7071,1830.5647,강서구,발산제1동,11500107,외발산동
519118,20200630,23,11500611,36117.4931,2101.2565,1126.3401,1237.5183,904.3129,914.7589,807.7308,...,1709.6884,1218.1782,1263.6770,1056.1983,771.6488,1872.8779,강서구,발산제1동,11500106,내발산동
519119,20200630,23,11500611,36117.4931,2101.2565,1126.3401,1237.5183,904.3129,914.7589,807.7308,...,1709.6884,1218.1782,1263.6770,1056.1983,771.6488,1872.8779,강서구,발산제1동,11500107,외발산동

In [ ]:
c = pd.merge(left=b,right=a2,how='right', left_on='행정동코드',right_on='행정동코드')

In [ ]:
len(c[c['행정동'].isna() ==True])

1

In [ ]:
# # 행정동 코드 
# # 유동인구 202006
# 2#LOCAL_PEOPLE_DONG_202006.csv
# for i in range(42) :
#     path = f'D:/데이터/유동인구/LOCAL_PEOPLE_DONG_{year[i]}.csv' 
#     b =pd.read_csv(path,encoding='utf-8')
#     # 주어진 데이터의 컬럼 파트가 3개 라인을 사용하고 있어서 실제 데이터가 아닌 부분도 데이터로 표현이 된다.
#     # Case.columns =  [ '케이스번호','도시이름','구이름','그룹유무','감염경로','몇번째확진자','위도','경도']
#     b.reset_index(inplace=True)
#     bcolumns = b.columns

#     b.drop('여자70세이상생활인구수',axis=1,inplace=True)
#     b.drop('여자55세부터59세생활인구수',axis=1,inplace=True)
#     b.drop('여자50세부터54세생활인구수',axis=1,inplace=True)
#     b.drop('여자65세부터69세생활인구수',axis=1,inplace=True)
#     b.drop('여자60세부터64세생활인구수',axis=1,inplace=True)
#     b.drop('여자45세부터49세생활인구수',axis=1,inplace=True)


#     b.columns =  bcolumns[6:]
#     print(i)
#     if i == 0 :
#         b0 =b
#     elif i ==1 :
#         realb =pd.concat([b,b0])
#     else :
#         realb = pd.concat([realb,b])

0
1
2

MemoryError:

In [ ]:
pip install pymysql

Collecting pymysqlNote: you may need to restart the kernel to use updated packages.

  Downloading PyMySQL-0.10.0-py2.py3-none-any.whl (47 kB)
Installing collected packages: pymysql
Successfully installed pymysql-0.10.0

In [ ]:
pip install sqlalchemy

Collecting sqlalchemy
  Downloading SQLAlchemy-1.3.18-cp37-cp37m-win32.whl (1.2 MB)
Installing collected packages: sqlalchemy
Successfully installed sqlalchemy-1.3.18
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# python <-> maridb (계열 mysql)
import pymysql
# 데이터베이스의 대량작업, 객체 연결등등 고차원 작업 진행 지원 모듈
from sqlalchemy import create_engine
# Dataframe을 sql에 전송하는 기능
import pandas.io.sql as pSql
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

In [ ]:
year1=list(map(lambda x: 201701+x, range(12))) 
year2=list(map(lambda x: 201801+x, range(2)))

year3=list(map(lambda x: 201803+x, range(5))) 
year4=list(map(lambda x: 201905+x, range(8))) 
year5= list(map(lambda x: 202002+x, range(5)))
year =year1+year2
len(year)
year3
year4
year5

[202002, 202003, 202004, 202005, 202006]

In [ ]:
# 행정동 코드 
# 유동인구 202006
2#LOCAL_PEOPLE_DONG_202006.csv

path = 'D:/데이터/유동인구/LOCAL_PEOPLE_DONG_201701.csv' 
df =pd.read_csv(path,sep=',',encoding='utf-8') 

# 주어진 데이터의 컬럼 파트가 3개 라인을 사용하고 있어서 실제 데이터가 아닌 부분도 데이터로 표현이 된다.
# Case.columns =  [ '케이스번호','도시이름','구이름','그룹유무','감염경로','몇번째확진자','위도','경도']
df.reset_index(inplace=True)
bcolumns = df.columns

df.drop('여자70세이상생활인구수',axis=1,inplace=True)
df.drop('여자55세부터59세생활인구수',axis=1,inplace=True)
df.drop('여자50세부터54세생활인구수',axis=1,inplace=True)
df.drop('여자65세부터69세생활인구수',axis=1,inplace=True)
df.drop('여자60세부터64세생활인구수',axis=1,inplace=True)
df.drop('여자45세부터49세생활인구수',axis=1,inplace=True)
df.columns =  bcolumns[6:]

In [ ]:
df.head()

,기준일ID,시간대구분,행정동코드,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
0,20170101,0,11110515,16846.9908,551.1680,351.2056,369.8000,1304.6177,850.2599,754.2146,...,476.3511,461.1296,625.6547,740.2699,756.2081,573.9838,473.3860,430.2336,350.5058,1206.3597
1,20170101,0,11110530,25606.3679,725.4355,322.4155,532.2063,1224.8244,1204.7807,1075.2772,...,1122.1443,890.0688,973.3847,980.6140,1161.5489,845.4654,749.9668,716.6214,498.2217,1844.1171
2,20170101,0,11110540,5724.9509,87.0075,66.6684,105.3054,524.3655,509.7949,358.1338,...,167.9036,155.2524,159.2981,153.4277,185.8502,157.4214,158.8650,146.5678,127.6351,447.9828
3,20170101,0,11110550,11691.6393,300.6513,233.1209,322.6515,411.5216,323.3993,295.2344,...,287.1489,331.9336,365.2763,512.1536,554.7413,456.3265,501.4379,437.0760,386.6049,1296.1468
4,20170101,0,11110560,24976.4805,590.4086,427.0619,631.2858,742.1176,616.4945,550.0281,...,598.5069,651.1402,897.7209,1010.2025,1112.7978,1069.6627,1170.9235,1090.1355,743.0981,3009.9850

In [ ]:
# 1. 연결 문자열 생성
id      = 'root'
pwd     = '12341234'
domain  = 'localhost'
port    = '3306'
database= 'test'
db_url  = f'mysql+pymysql://{id}:{pwd}@{domain}:{port}/{database}'
db_url

'mysql+pymysql://root:12341234@localhost:3306/test'

In [ ]:
# 2. 연결 엔진 생성
engine = create_engine( db_url, encoding='utf8' )
# 3. 실제 연결
conn = engine.connect()
# 4. 데이터 입력
df.to_sql( name='local_people_dong', con=conn, if_exists='append', index=False )
# 5. I/O를 수행하면 반드시 닫는다!!
conn.close()

In [ ]:
# 행정동 코드 
# 유동인구 202006
2#LOCAL_PEOPLE_DONG_202006.csv
# 201701~201802
for i in range(14) :
    path = f'D:/데이터/유동인구/LOCAL_PEOPLE_DONG_{year[i]}.csv' 
    df =pd.read_csv(path,sep=',',encoding='utf-8') 

    # 주어진 데이터의 컬럼 파트가 3개 라인을 사용하고 있어서 실제 데이터가 아닌 부분도 데이터로 표현이 된다.
    # Case.columns =  [ '케이스번호','도시이름','구이름','그룹유무','감염경로','몇번째확진자','위도','경도']
    df.reset_index(inplace=True)
    bcolumns = df.columns

    df.drop('여자70세이상생활인구수',axis=1,inplace=True)
    df.drop('여자55세부터59세생활인구수',axis=1,inplace=True)
    df.drop('여자50세부터54세생활인구수',axis=1,inplace=True)
    df.drop('여자65세부터69세생활인구수',axis=1,inplace=True)
    df.drop('여자60세부터64세생활인구수',axis=1,inplace=True)
    df.drop('여자45세부터49세생활인구수',axis=1,inplace=True)
    df.columns =  bcolumns[6:]
    # 2. 연결 엔진 생성
    engine = create_engine( db_url, encoding='utf8' )
    # 3. 실제 연결
    conn = engine.connect()
    # 4. 데이터 입력
    df.to_sql( name='local_people_dong', con=conn, if_exists='append', index=False )
    # 5. I/O를 수행하면 반드시 닫는다!!
    conn.close()

In [ ]:
path = f'D:/데이터/유동인구/LOCAL_PEOPLE_DONG_201803.csv' 
df =pd.read_csv(path,sep=',',encoding='utf-8') 

# 주어진 데이터의 컬럼 파트가 3개 라인을 사용하고 있어서 실제 데이터가 아닌 부분도 데이터로 표현이 된다.
# Case.columns =  [ '케이스번호','도시이름','구이름','그룹유무','감염경로','몇번째확진자','위도','경도']
# df.reset_index(inplace=True)
# bcolumns = df.columns

# df.drop('여자70세이상생활인구수',axis=1,inplace=True)
# df.drop('여자55세부터59세생활인구수',axis=1,inplace=True)
# df.drop('여자50세부터54세생활인구수',axis=1,inplace=True)
# df.drop('여자65세부터69세생활인구수',axis=1,inplace=True)
# df.drop('여자60세부터64세생활인구수',axis=1,inplace=True)
# df.drop('여자45세부터49세생활인구수',axis=1,inplace=True)
# df.columns =  bcolumns[6:]

In [ ]:
# 행정동 코드 
# 유동인구 202006
2#LOCAL_PEOPLE_DONG_202006.csv
#201803~201807 
for i in range(len(year3)) :
    path = f'D:/데이터/유동인구/LOCAL_PEOPLE_DONG_{year3[i]}.csv' 
    df =pd.read_csv(path,sep=',',encoding='utf-8') 
    df.reset_index(inplace=True)
    realcolumns = df.columns[1:]
    df.drop('여자70세이상생활인구수',axis=1,inplace=True)
    df.columns =  realcolumns
    # 2. 연결 엔진 생성
    engine = create_engine( db_url, encoding='utf8' )
    # 3. 실제 연결
    conn = engine.connect()
    # 4. 데이터 입력
    df.to_sql( name='local_people_dong', con=conn, if_exists='append', index=False )
    # 5. I/O를 수행하면 반드시 닫는다!!
    conn.close()

In [ ]:
# 행정동 코드 
# 유동인구 202006
2#LOCAL_PEOPLE_DONG_202006.csv
#201808~201807 
for i in range(len(year3)) :
    path = f'D:/데이터/유동인구/LOCAL_PEOPLE_DONG_{year3[i]}.csv' 
    df =pd.read_csv(path,sep=',',encoding='utf-8') 
    df.reset_index(inplace=True)
    realcolumns = df.columns[1:]
    df.drop('여자70세이상생활인구수',axis=1,inplace=True)
    df.columns =  realcolumns
    # 2. 연결 엔진 생성
    engine = create_engine( db_url, encoding='utf8' )
    # 3. 실제 연결
    conn = engine.connect()
    # 4. 데이터 입력
    df.to_sql( name='local_people_dong', con=conn, if_exists='append', index=False )
    # 5. I/O를 수행하면 반드시 닫는다!!
    conn.close()

In [ ]:
path = f'D:/데이터/유동인구/LOCAL_PEOPLE_DONG_201808.csv' 
df =pd.read_csv(path,sep=',',encoding='utf-8') 
df.reset_index(inplace=True)
bcolumns = df.columns

df.drop('여자70세이상생활인구수',axis=1,inplace=True)
df.drop('여자55세부터59세생활인구수',axis=1,inplace=True)
df.drop('여자50세부터54세생활인구수',axis=1,inplace=True)
df.drop('여자65세부터69세생활인구수',axis=1,inplace=True)
df.drop('여자60세부터64세생활인구수',axis=1,inplace=True)
df.drop('여자45세부터49세생활인구수',axis=1,inplace=True)
df.columns =  bcolumns[6:]
# 2. 연결 엔진 생성
engine = create_engine( db_url, encoding='utf8' )
# 3. 실제 연결
conn = engine.connect()
# 4. 데이터 입력
df.to_sql( name='local_people_dong', con=conn, if_exists='append', index=False )
# 5. I/O를 수행하면 반드시 닫는다!!
conn.close()

In [ ]:
path = f'D:/데이터/유동인구/LOCAL_PEOPLE_DONG_201809.csv' 
df =pd.read_csv(path,sep=',',encoding='utf-8') 
df.reset_index(inplace=True)
bcolumns = df.columns

df.drop('여자70세이상생활인구수',axis=1,inplace=True)
df.drop('여자55세부터59세생활인구수',axis=1,inplace=True)
df.drop('여자50세부터54세생활인구수',axis=1,inplace=True)
df.drop('여자65세부터69세생활인구수',axis=1,inplace=True)
df.drop('여자60세부터64세생활인구수',axis=1,inplace=True)
df.drop('여자45세부터49세생활인구수',axis=1,inplace=True)
df.columns =  bcolumns[6:]
# 2. 연결 엔진 생성
engine = create_engine( db_url, encoding='utf8' )
# 3. 실제 연결
conn = engine.connect()
# 4. 데이터 입력
df.to_sql( name='local_people_dong', con=conn, if_exists='append', index=False )
# 5. I/O를 수행하면 반드시 닫는다!!
conn.close()

In [ ]:
path = f'D:/데이터/유동인구/LOCAL_PEOPLE_DONG_201810.csv' 
df =pd.read_csv(path,sep=',',encoding='utf-8') 
df.reset_index(inplace=True)
realcolumns = df.columns[1:]
df.drop('여자70세이상생활인구수',axis=1,inplace=True)
df.columns =  realcolumns
# 2. 연결 엔진 생성
engine = create_engine( db_url, encoding='utf8' )
# 3. 실제 연결
conn = engine.connect()
# 4. 데이터 입력
df.to_sql( name='local_people_dong', con=conn, if_exists='append', index=False )
# 5. I/O를 수행하면 반드시 닫는다!!
conn.close()

In [ ]:
path = f'D:/데이터/유동인구/LOCAL_PEOPLE_DONG_201811.csv' 
df =pd.read_csv(path,sep=',',encoding='utf-8',error_bad_lines=False) 
df.reset_index(inplace=True)
realcolumns = df.columns[1:]
df.drop('여자70세이상생활인구수',axis=1,inplace=True)
df.columns =  realcolumns
df

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

,기준일ID,시간대구분,행정동코드,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
0,20181101,0,11110515,14799.0314,489.8446,312.1301,493.4818,484.2561,463.3706,486.0634,...,442.1121,483.7973,694.3211,768.4976,803.8630,572.8530,476.6775,407.1267,491.9050,1274.6222
1,20181101,0,11110540,5072.4639,68.5522,52.5271,331.0671,252.8436,172.7127,179.7855,...,122.8208,142.8454,200.8265,185.8934,155.6270,186.6237,198.3063,185.9573,171.8843,503.2241
2,20181101,0,11110550,13510.7258,296.9959,230.2863,355.1712,530.7080,438.1504,361.4088,...,382.5184,437.4985,541.8144,493.2076,642.4960,655.1849,488.8321,612.6179,323.6644,1417.2739
3,20181101,0,11110560,22047.6664,631.9267,457.0936,632.7882,612.5082,608.7870,513.3366,...,467.2121,570.1048,795.0337,781.8997,1067.2416,932.3145,1074.0614,1025.2258,747.4158,2495.0940
4,20181101,0,11170530,10764.3579,210.1115,101.3827,195.1805,562.6486,550.6451,562.9493,...,544.9739,479.1962,453.2349,330.4576,335.1968,313.0150,367.0382,299.8554,234.3563,519.1046
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223867,20181122,23,11200550,22422.1069,301.7550,137.5647,1127.1110,3624.8500,2338.2160,865.5996,...,1363.6967,728.2569,422.9370,367.3534,425.2814,448.4808,429.9726,376.2949,294.6657,985.5308
223868,20181122,23,11305534,28352.7072,1082.9933,616.6897,735.1900,788.6641,851.6639,805.8502,...,819.4034,813.1773,1037.8623,977.4020,1128.9517,1190.7871,1182.3156,1081.2066,997.9656,2732.1644
223869,20181122,23,11590670,19779.1202,667.9268,431.0042,489.0014,505.3412,626.5481,729.5364,...,831.9359,819.4290,811.2781,872.7319,860.6617,727.7432,846.8471,703.2236,546.4175,1407.4702
223870,20181122,23,11470610,5341.2188,225.4574,147.4146,168.2139,138.5260,138.1975,158.3186,...,142.2108,157.3125,219.0989,225.4703,209.1859,226.1093,269.0144,236.2098,182.1611,381.5675
223871,20181122,23,11320670,19121.0121,733.0656,377.2679,538.8825,618.6696,633.6334,657.8303,...,634.8657,686.1895,758.7821,641.5852,798.0692,775.4385,907.2487,860.5427,592.6268,1687.7582

In [ ]:
df

,기준일ID,시간대구분,행정동코드,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
0,20181101,0,11110515,14799.0314,489.8446,312.1301,493.4818,484.2561,463.3706,486.0634,...,442.1121,483.7973,694.3211,768.4976,803.8630,572.8530,476.6775,407.1267,491.9050,1274.6222
1,20181101,0,11110540,5072.4639,68.5522,52.5271,331.0671,252.8436,172.7127,179.7855,...,122.8208,142.8454,200.8265,185.8934,155.6270,186.6237,198.3063,185.9573,171.8843,503.2241
2,20181101,0,11110550,13510.7258,296.9959,230.2863,355.1712,530.7080,438.1504,361.4088,...,382.5184,437.4985,541.8144,493.2076,642.4960,655.1849,488.8321,612.6179,323.6644,1417.2739
3,20181101,0,11110560,22047.6664,631.9267,457.0936,632.7882,612.5082,608.7870,513.3366,...,467.2121,570.1048,795.0337,781.8997,1067.2416,932.3145,1074.0614,1025.2258,747.4158,2495.0940
4,20181101,0,11170530,10764.3579,210.1115,101.3827,195.1805,562.6486,550.6451,562.9493,...,544.9739,479.1962,453.2349,330.4576,335.1968,313.0150,367.0382,299.8554,234.3563,519.1046
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223867,20181122,23,11200550,22422.1069,301.7550,137.5647,1127.1110,3624.8500,2338.2160,865.5996,...,1363.6967,728.2569,422.9370,367.3534,425.2814,448.4808,429.9726,376.2949,294.6657,985.5308
223868,20181122,23,11305534,28352.7072,1082.9933,616.6897,735.1900,788.6641,851.6639,805.8502,...,819.4034,813.1773,1037.8623,977.4020,1128.9517,1190.7871,1182.3156,1081.2066,997.9656,2732.1644
223869,20181122,23,11590670,19779.1202,667.9268,431.0042,489.0014,505.3412,626.5481,729.5364,...,831.9359,819.4290,811.2781,872.7319,860.6617,727.7432,846.8471,703.2236,546.4175,1407.4702
223870,20181122,23,11470610,5341.2188,225.4574,147.4146,168.2139,138.5260,138.1975,158.3186,...,142.2108,157.3125,219.0989,225.4703,209.1859,226.1093,269.0144,236.2098,182.1611,381.5675
223871,20181122,23,11320670,19121.0121,733.0656,377.2679,538.8825,618.6696,633.6334,657.8303,...,634.8657,686.1895,758.7821,641.5852,798.0692,775.4385,907.2487,860.5427,592.6268,1687.7582

In [ ]:
# 201811 

# 2. 연결 엔진 생성
engine = create_engine( db_url, encoding='utf8' )
# 3. 실제 연결
conn = engine.connect()
# 4. 데이터 입력
df.to_sql( name='local_people_dong', con=conn, if_exists='append', index=False )
# 5. I/O를 수행하면 반드시 닫는다!!
conn.close()

In [ ]:
path = f'D:/데이터/유동인구/LOCAL_PEOPLE_DONG_201812.csv' 
df =pd.read_csv(path,sep=',',encoding='utf-8')
df.reset_index(inplace=True)
bcolumns = df.columns

df.drop('여자70세이상생활인구수',axis=1,inplace=True)
df.drop('여자55세부터59세생활인구수',axis=1,inplace=True)
df.drop('여자50세부터54세생활인구수',axis=1,inplace=True)
df.drop('여자65세부터69세생활인구수',axis=1,inplace=True)
df.drop('여자60세부터64세생활인구수',axis=1,inplace=True)
df.drop('여자45세부터49세생활인구수',axis=1,inplace=True)
df.columns =  bcolumns[6:]
# 2. 연결 엔진 생성
engine = create_engine( db_url, encoding='utf8' )
# 3. 실제 연결
conn = engine.connect()
# 4. 데이터 입력
df.to_sql( name='local_people_dong', con=conn, if_exists='append', index=False )
# 5. I/O를 수행하면 반드시 닫는다!!
conn.close()

In [ ]:
path = f'D:/데이터/유동인구/LOCAL_PEOPLE_DONG_201901.csv' 
df =pd.read_csv(path,sep=',',encoding='utf-8')
df.reset_index(inplace=True)
bcolumns = df.columns

df.drop('여자70세이상생활인구수',axis=1,inplace=True)
df.drop('여자55세부터59세생활인구수',axis=1,inplace=True)
df.drop('여자50세부터54세생활인구수',axis=1,inplace=True)
df.drop('여자65세부터69세생활인구수',axis=1,inplace=True)
df.drop('여자60세부터64세생활인구수',axis=1,inplace=True)
df.drop('여자45세부터49세생활인구수',axis=1,inplace=True)
df.columns =  bcolumns[6:]
# 2. 연결 엔진 생성
engine = create_engine( db_url, encoding='utf8' )
# 3. 실제 연결
conn = engine.connect()
# 4. 데이터 입력
df.to_sql( name='local_people_dong', con=conn, if_exists='append', index=False )
# 5. I/O를 수행하면 반드시 닫는다!!
conn.close()

In [ ]:
path = f'D:/데이터/유동인구/LOCAL_PEOPLE_DONG_201902.csv' 
df =pd.read_csv(path,sep=',',encoding='utf-8')
df.reset_index(inplace=True)
realcolumns = df.columns[1:]
df.drop('여자70세이상생활인구수',axis=1,inplace=True)
df.columns =  realcolumns
# 2. 연결 엔진 생성
engine = create_engine( db_url, encoding='utf8' )
# 3. 실제 연결
conn = engine.connect()
# 4. 데이터 입력
df.to_sql( name='local_people_dong', con=conn, if_exists='append', index=False )
# 5. I/O를 수행하면 반드시 닫는다!!
conn.close()

In [ ]:
path = f'D:/데이터/유동인구/LOCAL_PEOPLE_DONG_201903.csv' 
df =pd.read_csv(path,sep=',',encoding='utf-8')
df.reset_index(inplace=True)
bcolumns = df.columns

df.drop('여자70세이상생활인구수',axis=1,inplace=True)
df.drop('여자55세부터59세생활인구수',axis=1,inplace=True)
df.drop('여자50세부터54세생활인구수',axis=1,inplace=True)
df.drop('여자65세부터69세생활인구수',axis=1,inplace=True)
df.drop('여자60세부터64세생활인구수',axis=1,inplace=True)
df.drop('여자45세부터49세생활인구수',axis=1,inplace=True)
df.columns =  bcolumns[6:]
# 2. 연결 엔진 생성
engine = create_engine( db_url, encoding='utf8' )
# 3. 실제 연결
conn = engine.connect()
# 4. 데이터 입력
df.to_sql( name='local_people_dong', con=conn, if_exists='append', index=False )
# 5. I/O를 수행하면 반드시 닫는다!!
conn.close()

In [ ]:
path = f'D:/데이터/유동인구/LOCAL_PEOPLE_DONG_201904.csv' 
df =pd.read_csv(path,sep=',',encoding='utf-8')
df.reset_index(inplace=True)
realcolumns = df.columns[1:]
df.drop('여자70세이상생활인구수',axis=1,inplace=True)
df.columns =  realcolumns
# 2. 연결 엔진 생성
engine = create_engine( db_url, encoding='utf8' )
# 3. 실제 연결
conn = engine.connect()
# 4. 데이터 입력
df.to_sql( name='local_people_dong', con=conn, if_exists='append', index=False )
# 5. I/O를 수행하면 반드시 닫는다!!
conn.close()

In [ ]:
#2019-05 ~ 2019-12
for i in range(len(year4)) :
    path = f'D:/데이터/유동인구/LOCAL_PEOPLE_DONG_{year4[i]}.csv' 
    df =pd.read_csv(path,sep=',',encoding='utf-8')
    df.reset_index(inplace=True)
    realcolumns = df.columns[1:]
    df.drop('여자70세이상생활인구수',axis=1,inplace=True)
    df.columns =  realcolumns
    # 2. 연결 엔진 생성
    engine = create_engine( db_url, encoding='utf8' )
    # 3. 실제 연결
    conn = engine.connect()
    # 4. 데이터 입력
    df.to_sql( name='local_people_dong', con=conn, if_exists='append', index=False )
    # 5. I/O를 수행하면 반드시 닫는다!!
    conn.close()

In [ ]:
path = f'D:/데이터/유동인구/LOCAL_PEOPLE_DONG_202001.csv' 
df =pd.read_csv(path,sep=',',encoding='utf-8')
df.reset_index(inplace=True)
bcolumns = df.columns

df.drop('여자70세이상생활인구수',axis=1,inplace=True)
df.drop('여자55세부터59세생활인구수',axis=1,inplace=True)
df.drop('여자50세부터54세생활인구수',axis=1,inplace=True)
df.drop('여자65세부터69세생활인구수',axis=1,inplace=True)
df.drop('여자60세부터64세생활인구수',axis=1,inplace=True)
df.drop('여자45세부터49세생활인구수',axis=1,inplace=True)
df.columns =  bcolumns[6:]
 # 2. 연결 엔진 생성
engine = create_engine( db_url, encoding='utf8' )
# 3. 실제 연결
conn = engine.connect()
# 4. 데이터 입력
df.to_sql( name='local_people_dong', con=conn, if_exists='append', index=False )
# 5. I/O를 수행하면 반드시 닫는다!!
conn.close()

In [ ]:
#202002~202006
for i in range(len(year5)) :
    path = f'D:/데이터/유동인구/LOCAL_PEOPLE_DONG_{year5[i]}.csv' 
    df =pd.read_csv(path,sep=',',encoding='utf-8')
    df.reset_index(inplace=True)
    realcolumns = df.columns[1:]
    df.drop('여자70세이상생활인구수',axis=1,inplace=True)
    df.columns =  realcolumns
 # 2. 연결 엔진 생성
    engine = create_engine( db_url, encoding='utf8' )
    # 3. 실제 연결
    conn = engine.connect()
    # 4. 데이터 입력
    df.to_sql( name='local_people_dong', con=conn, if_exists='append', index=False )
    # 5. I/O를 수행하면 반드시 닫는다!!
    conn.close()

,기준일ID,시간대구분,행정동코드,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
0,20200201,0,11440730,40008.7419,1346.3171,841.9587,1061.1255,1050.6067,1347.5052,1493.9572,...,2149.2173,1937.7415,1978.4616,1743.0507,1825.5686,1429.1436,1257.2309,1227.2301,958.5541,2808.6218
1,20200201,0,11650621,26212.2534,789.3616,519.2963,864.9748,627.7166,837.1151,905.2537,...,1033.6004,995.9951,1162.6565,1138.2961,1314.2640,991.8098,948.0337,918.3349,666.0662,1971.8968
2,20200201,0,11215830,23724.4049,762.3188,356.6239,562.7924,617.7153,875.1754,1006.7162,...,1013.5383,1147.8351,1191.2545,915.0628,902.7632,902.2134,1049.6805,904.8118,644.3256,1455.1883
3,20200201,0,11290770,14879.6820,554.3716,386.5561,318.8035,397.4454,476.9146,386.7727,...,500.0448,367.2178,508.3087,494.4807,667.0206,582.6305,637.4483,593.1703,475.5271,1315.0792
4,20200201,0,11305555,30307.1826,998.5169,552.0452,733.2881,732.6588,914.3310,881.1347,...,933.2675,1002.1755,1096.1847,1041.6831,1303.0572,1241.5933,1328.6948,1201.8803,947.3990,3024.0821
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295099,20200229,23,11110550,15557.0453,420.3440,325.9288,409.4950,510.4730,466.4657,403.0718,...,447.2245,432.2969,607.0418,601.2681,808.5061,704.6807,712.5709,650.5586,409.1535,1574.4560
295100,20200229,23,11110630,9260.5173,113.2755,86.2242,141.0809,340.4600,533.2121,430.3509,...,457.4560,236.3920,271.7890,225.8560,299.1148,377.2973,384.6535,405.9373,260.5514,781.0234
295101,20200229,23,11110580,6347.2259,326.8050,130.0039,178.3367,155.1779,182.7959,176.0912,...,224.6530,220.6510,256.5878,239.6820,305.3205,239.6718,204.3535,199.7958,171.0140,469.4681
295102,20200229,23,11110615,21882.7250,288.8278,91.0007,278.1021,1360.0591,2369.4164,1453.8977,...,1042.7972,647.8581,596.4171,475.7010,539.0135,434.4506,621.9553,471.9550,400.2289,1099.2019
295103,20200229,23,11110600,4972.7796,46.4308,32.7747,99.2992,184.1629,189.1157,157.0845,...,155.4113,171.5923,223.8222,209.1527,286.5395,209.3843,213.4942,183.6655,144.5968,398.0780

In [ ]:
import folium

In [ ]:
folium.__version__

In [ ]:
# gps =[37.5511694,126.9860379]
# map = folium.Map(location= gps ,zoom_start= 11)
# for i in seoul[['위도','경도','거점명']].values:
#     folium.Marker([i[0]	,i[1]],popup=i[2],icon= folium.Icon(icon='cloud')).add_to(map)
# map

In [ ]:
# ab= aa.iloc[:,0:3]
# ab.drop_duplicates('행정동코드',inplace=True)
# ab